# Generated by Django 2.1 on 2018-12-05 18:12

from django.db import migrations
from django.db import connection
from django.db.utils import ProgrammingError
from django.db import transaction

SQL = [
    'ALTER TABLE offline_messages_offlinemessage ADD COLUMN level INTEGER;',
    'ALTER TABLE offline_messages_offlinemessage ADD COLUMN read boolean;',
    'ALTER TABLE offline_messages_offlinemessage ADD COLUMN object_id INTEGER;',
    'ALTER TABLE offline_messages_offlinemessage ADD COLUMN meta jsonb;',
    'ALTER TABLE offline_messages_offlinemessage ADD COLUMN content_type_id INTEGER;',
]

def mig(apps, schema_editor):
    with connection.cursor() as cursor:
        for sql in SQL:
            try:
                with transaction.atomic():
                    cursor.execute(sql)
            except ProgrammingError:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('offline_messages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(mig),
    ]
